### ISSUE TITLE
How to tokenize the text into several phrases?

### ISSUE THREAD

**Issue by RyanLiut** [UniversalDependencies/UD_Classical_Chinese-Kyoto#2]
Hi,

Thank you for the code.

But it seems that it cannot tokenize the text into several phrases, but just each character for a token after applying the `tokenize` processor?

Thank you

**Comment by KoichiYasuoka** [comment]
First of all, @RyanLiut, UD_Classical_Chinese-Kyoto is a **corpus**, not a code.

> But it seems that it cannot tokenize the text into several phrases, but just each character for a token after applying the `tokenize` processor?

We (my colleagues and I) have prepared several python packages to process Classical Chinese texts: [roberta-classical-chinese-large-sentence-segmentation](https://huggingface.co/KoichiYasuoka/roberta-classical-chinese-large-sentence-segmentation) and [roberta-classical-chinese-base-sentence-segmentation](https://huggingface.co/KoichiYasuoka/roberta-classical-chinese-base-sentence-segmentation) for sentence segmentation (phrase tokenization), [roberta-classical-chinese-large-upos](https://huggingface.co/KoichiYasuoka/roberta-classical-chinese-large-upos) and [roberta-classical-chinese-base-upos](https://huggingface.co/KoichiYasuoka/roberta-classical-chinese-base-upos) for Part-Of-Speech tagging (with word tokenization), [SuPar-Kanbun](https://github.com/KoichiYasuoka/SuPar-Kanbun) for the processing pipeline. Please use them in your python environment.
