### ISSUE TITLE
UDPipe Visualizer with Immediate Catena Tree

### ISSUE THREAD

**Issue by wongtaksum** [UniversalDependencies/UD_Classical_Chinese-Kyoto#6]
I just visited http://kanji.zinbun.kyoto-u.ac.jp/~yasuoka/kyodokenkyu/2020-04-24/UDPipeICT.html
and found that the first three selections do not work, namely 中文, 漢文+MeCab, 漢文.

**Comment by KoichiYasuoka** [comment]
I've just rebooted my UD-Pipe server. Please confirm it can work now.
